/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package management.views.fish;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;

import javax.swing.table.DefaultTableModel;
import javax.swing.JTextField;
import javax.swing.JOptionPane;

import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Asriel
 */
public class fishJFrame extends javax.swing.JFrame {

    /**
     * Creates new form fishJFrame
     */
    public fishJFrame() {
        initComponents();
        refreshFishData("postgres", "postgres");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allPanel = new javax.swing.JPanel();
        functionPanel = new javax.swing.JPanel();
        refreshButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        idSearch = new javax.swing.JTextField();
        nameSearch = new javax.swing.JTextField();
        tempCHighSearch = new javax.swing.JTextField();
        tempCLowSearch = new javax.swing.JTextField();
        humidityHighSearch = new javax.swing.JTextField();
        humidityLowSearch = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fishDataTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        allPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        refreshButton.setText("Làm mới");
        refreshButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshButtonMouseClicked(evt);
            }
        });

        addButton.setText("Thêm");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });

        delButton.setText("jButton1");

        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout functionPanelLayout = new javax.swing.GroupLayout(functionPanel);
        functionPanel.setLayout(functionPanelLayout);
        functionPanelLayout.setHorizontalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(functionPanelLayout.createSequentialGroup()
                        .addComponent(tempCHighSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(humidityHighSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(functionPanelLayout.createSequentialGroup()
                        .addComponent(tempCLowSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(humidityLowSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(refreshButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delButton)))
                .addContainerGap())
        );
        functionPanelLayout.setVerticalGroup(
            functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionPanelLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempCHighSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(humidityHighSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(functionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshButton)
                    .addComponent(addButton)
                    .addComponent(delButton)
                    .addComponent(idSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempCLowSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(humidityLowSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        fishDataTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fishDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên loại cá", "Nhiệt độ trên", "Nhiệt độ dưới", "Độ ẩm trên", "Độ ẩm dưới"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fishDataTable.setShowGrid(true);
        fishDataTable.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(fishDataTable);
        if (fishDataTable.getColumnModel().getColumnCount() > 0) {
            fishDataTable.getColumnModel().getColumn(0).setResizable(false);
            fishDataTable.getColumnModel().getColumn(1).setResizable(false);
            fishDataTable.getColumnModel().getColumn(2).setResizable(false);
            fishDataTable.getColumnModel().getColumn(3).setResizable(false);
            fishDataTable.getColumnModel().getColumn(4).setResizable(false);
            fishDataTable.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout allPanelLayout = new javax.swing.GroupLayout(allPanel);
        allPanel.setLayout(allPanelLayout);
        allPanelLayout.setHorizontalGroup(
            allPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        allPanelLayout.setVerticalGroup(
            allPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allPanelLayout.createSequentialGroup()
                .addComponent(functionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
        );

        getContentPane().add(allPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void refreshFishData(String username, String password){
        Connection connection = null;
        
        DefaultTableModel tModel = (DefaultTableModel) fishDataTable.getModel();
        tModel.setRowCount(0);
        
        try {            
            Class.forName("org.postgresql.Driver");
            connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", username, password);
            
            Statement st = connection.createStatement();
            String query = "SELECT * FROM danhmuc_ca;";
            ResultSet rs = st.executeQuery(query);
            
            while (rs.next()){
                String id = String.valueOf(rs.getString(1));
                String name = String.valueOf(rs.getString(2));
                String tempC_high = String.valueOf(String.format("%.2g%n", rs.getFloat(3)));
                String tempC_low  = String.valueOf(String.format("%.2g%n", rs.getFloat(4)));
                String humidity_high = String.valueOf(String.format("%.2g%n", rs.getFloat(5)));
                String humidity_low  = String.valueOf(String.format("%.2g%n", rs.getFloat(6)));
                
                String storageData[] = {id, name, tempC_high, tempC_low, humidity_high, humidity_low};
                
                tModel.addRow(storageData);
            }
        }
        catch (Exception e){
            System.out.println(e);
        }
    }
    
    private static boolean isTextFieldEmpty(JTextField textField) {
        return textField.getText().trim().isEmpty();
    }
    
    //TODO: Them truong hop chi lay tren/duoi
    private void searchFishData(String username, String password){
        Connection connection = null;
        String query = "";
        
        boolean id_null = isTextFieldEmpty(idSearch);
        boolean name_null = isTextFieldEmpty(nameSearch);
        boolean tempC_high_null = isTextFieldEmpty(tempCHighSearch);
        boolean tempC_low_null = isTextFieldEmpty(tempCLowSearch);
        boolean humidity_high_null = isTextFieldEmpty(humidityHighSearch);
        boolean humidity_low_null = isTextFieldEmpty(humidityLowSearch);
        
        
        List<String> conditions = new ArrayList<>();
        if (!id_null){
            conditions.add("ma_loaica = '" + String.valueOf(idSearch.getText()) + "'");
        }
        if (!name_null){
            conditions.add("ten_loaica = '" + String.valueOf(nameSearch.getText()) + "'");
        }
        
        if (tempC_high_null && !tempC_low_null || !tempC_high_null && tempC_low_null){
            JOptionPane.showMessageDialog(null, "Đôi với nhiệt độ cần cả 2 ngưỡng trên và dưới", "Nhập thiếu dữ liệu", JOptionPane.WARNING_MESSAGE);
        }
        if (!tempC_high_null && !tempC_low_null){
            conditions.add("nhietdo_tren <= " + String.valueOf(tempCHighSearch.getText()) + " AND " + "nhietdo_duoi >= " + String.valueOf(tempCLowSearch.getText()));
        }
        
        if (humidity_high_null && !humidity_low_null || !humidity_high_null && humidity_low_null){
            JOptionPane.showMessageDialog(null, "Đôi với độ ẩm cần cả 2 ngưỡng trên và dưới", "Nhập thiếu dữ liệu", JOptionPane.WARNING_MESSAGE);
        }
        if (!humidity_high_null && !humidity_low_null){
            conditions.add("doam_tren <= " + String.valueOf(humidityHighSearch.getText()) + " AND " + "doam_duoi >= " + String.valueOf(humidityLowSearch.getText()));
        }
        
        DefaultTableModel tModel = (DefaultTableModel) fishDataTable.getModel();
        tModel.setRowCount(0);
        
        try {
            Class.forName("org.postgresql.Driver");
            connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", username, password);
            
            
            Statement st = connection.createStatement();
            query = "SELECT * FROM danhmuc_ca";
            if (!conditions.isEmpty()) {
                query += " WHERE ";
                query += String.join(" AND ", conditions);
            } 
            System.out.println(query);
            ResultSet rs = st.executeQuery(query);
            
            while (rs.next()){
                String id = String.valueOf(rs.getString(1));
                String name = String.valueOf(rs.getString(2));
                String tempC_high = String.valueOf(String.format("%.2g%n", rs.getFloat(3)));
                String tempC_low  = String.valueOf(String.format("%.2g%n", rs.getFloat(4)));
                String humidity_high = String.valueOf(String.format("%.2g%n", rs.getFloat(5)));
                String humidity_low  = String.valueOf(String.format("%.2g%n", rs.getFloat(6)));
                
                String storageData[] = {id, name, tempC_high, tempC_low, humidity_high, humidity_low};
                
                tModel.addRow(storageData);
            }
            
        }
        catch (Exception e){
            System.out.println(e);
        }
    }
    
    private void refreshButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshButtonMouseClicked
        refreshFishData("postgres", "postgres");
    }//GEN-LAST:event_refreshButtonMouseClicked

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        searchFishData("postgres", "postgres");
    }//GEN-LAST:event_searchButtonMouseClicked

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        newFishJFrame addFishDataFrame = new newFishJFrame();
        addFishDataFrame.setVisible(true);
    }//GEN-LAST:event_addButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fishJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fishJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fishJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fishJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fishJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel allPanel;
    private javax.swing.JButton delButton;
    private javax.swing.JTable fishDataTable;
    private javax.swing.JPanel functionPanel;
    private javax.swing.JTextField humidityHighSearch;
    private javax.swing.JTextField humidityLowSearch;
    private javax.swing.JTextField idSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameSearch;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField tempCHighSearch;
    private javax.swing.JTextField tempCLowSearch;
    // End of variables declaration//GEN-END:variables
}
