/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package management.views.fish;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

/**
 *
 * @author Asriel
 */
public class newFishJFrame extends javax.swing.JFrame {

    /**
     * Creates new form newFishJFrame
     */
    public newFishJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allPanel = new javax.swing.JPanel();
        fishId = new javax.swing.JTextField();
        fishName = new javax.swing.JTextField();
        humidityUp = new javax.swing.JTextField();
        humidityLow = new javax.swing.JTextField();
        tempCUp = new javax.swing.JTextField();
        tempCLow = new javax.swing.JTextField();
        fishNote = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        allPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        allPanel.add(fishId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 260, -1));
        allPanel.add(fishName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 260, -1));
        allPanel.add(humidityUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 71, -1));
        allPanel.add(humidityLow, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 71, -1));
        allPanel.add(tempCUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 71, -1));
        allPanel.add(tempCLow, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 71, -1));
        allPanel.add(fishNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 400, 120));

        jLabel1.setText("Tên loài cá");
        allPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 60, 20));

        jLabel2.setText("Mã loại cá");
        allPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 20));

        jLabel3.setText("Độ ẩm dưới");
        allPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 70, -1));

        jLabel5.setText("Độ ẩm trên");
        allPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 70, -1));

        jLabel4.setText("Nhiệt độ dưới");
        allPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel6.setText("Nhiệt độ trên");
        allPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel7.setText("Ghi chú");
        allPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        cancelButton.setText("Hủy");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        allPanel.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        confirmButton.setText("Xác nhận");
        confirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmButtonMouseClicked(evt);
            }
        });
        allPanel.add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(allPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(allPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        dispose();
    }//GEN-LAST:event_cancelButtonMouseClicked

    
//TODO: Thêm các trường hợp ngọại lệ
    private void confirmButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmButtonMouseClicked
        Connection connection = null;
        PreparedStatement pstmt = null;
        
        String id = String.valueOf(fishId.getText());
        String name = String.valueOf(fishName.getText());
        
        float _tempC_up = Float.parseFloat(tempCUp.getText());
        float _tempC_low = Float.parseFloat(tempCLow.getText());
        float _humidity_up = Float.parseFloat(humidityUp.getText());
        float _humidity_low = Float.parseFloat(humidityLow.getText());
        
        String note = String.valueOf(fishNote.getText());
        
        try {
            Class.forName("org.postgresql.Driver");
            connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "postgres");
            
            String query = "INSERT INTO danhmuc_ca VALUES(?, ?, ?, ?, ?, ?, ?); "; 
            pstmt = connection.prepareStatement(query);
            
            pstmt.setString(1, id);
            pstmt.setString(2, name);
            pstmt.setFloat(3, _tempC_up);
            pstmt.setFloat(4, _tempC_low);
            pstmt.setFloat(5, _humidity_up);
            pstmt.setFloat(6, _humidity_low);
            pstmt.setString(7, note);
            
            int status = pstmt.executeUpdate();
            if (status > 0)
                System.out.println("INSERTED");
            else 
                System.out.println("SOMETHING WRONG");
            
        } catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_confirmButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newFishJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newFishJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newFishJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newFishJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newFishJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField fishId;
    private javax.swing.JTextField fishName;
    private javax.swing.JTextField fishNote;
    private javax.swing.JTextField humidityLow;
    private javax.swing.JTextField humidityUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tempCLow;
    private javax.swing.JTextField tempCUp;
    // End of variables declaration//GEN-END:variables
}
